/* Browser controls and measurements. None of the rendering or outcome checks feed back into the physics. */
(function(){'use strict';
const {Model,W,S}=ContinuityPhysics;
const params=new URLSearchParams(location.search),raw=Number(params.get('seed')),seed=(Number.isFinite(raw)&&raw>0?raw:717171)>>>0;
let baseline,paused=false,experiments=[],last=0,ready=false;
const defs=[
 {id:'assembly',n:'01',title:'Assembly',q:'Can scattered concentrations become one persistent body?',action:'Watch assembly',do:'Start with the noisy chemical seed. The faint control has the same seed but no catalytic coupling. No ring, silhouette or neighbour graph is supplied.',why:'One continuous boundary appears from many local reactions. The organization is generated, not reassembled from numbered slots.',quote:'Experiment is the sole judge of scientific “truth.”',author:'Richard Feynman · The Feynman Lectures, I–1',url:'https://www.feynmanlectures.caltech.edu/I_01.html'},
 {id:'turnover',n:'02',title:'Turnover',q:'Can the body stay while its original material leaves?',action:'Replace the matter',do:'The bath exchanges old precursor for an equal amount of new precursor. A real tracer follows old material through breakdown and resynthesis: pale becomes gold as new material is incorporated.',why:'The material history changes while the density evolution matches the untreated control. The label is chemically neutral by assumption; this is not a proof about human identity.',quote:'This world is mere change, and this life, opinion.',author:'Marcus Aurelius · Meditations, Book IV',url:'https://www.gutenberg.org/files/2680/2680-h/2680-h.htm'},
 {id:'wound',n:'03',title:'Wound / repair',q:'Will a real hole close without a repair command?',action:'Puncture the body',do:'Tap the body or use the button. A patch of active material becomes dissolved precursor. Inspect the hole for a moment; then the unmodified chemical rules continue.',why:'The missing region fills because surviving chemistry and local transport remain active—not because anything remembers where the boundary belongs.',quote:'There is grandeur in this view of life',author:'Charles Darwin · On the Origin of Species, conclusion',url:'https://www.gutenberg.org/files/1228/1228-h/1228-h.htm'},
 {id:'memory',n:'04',title:'Memory / scar',q:'Does the past leave a measurable difference after the input ends?',action:'Train & release',do:'Both samples receive the same local chemical pulse. Only the main sample can retain a slow catalytic trace, shown in coral. The thumbnail receives the pulse but cannot store the trace.',why:'After the stimulus ends, the remaining material state changes future chemistry. This is chemical history, not consciousness or a memory of the whole body.',quote:'the possession of a structure weak enough to yield to an influence, but strong enough not to yield all at once.',author:'William James · The Principles of Psychology, “Habit”',url:'https://psychclassics.yorku.ca/James/Principles/prin4.htm'},
 {id:'lost',n:'05',title:'Relations lost',q:'What vanishes when the material is still here?',action:'Disable coupling',do:'Block the reaction that lets A and B sustain each other. The active body decays into the visible dissolved bath. Nothing is deleted from the material total.',why:'A body can disappear without its matter leaving. Compare the lost high-density outline with the unchanged total-material measurement.',quote:'the whole is something beside the parts',author:'Aristotle · Metaphysics VIII.6, W. D. Ross translation',url:'https://classics.mit.edu/Aristotle/metaphysics.8.viii.html'},
 {id:'restore',n:'06',title:'Relations restored',q:'Does restoring the rule restore the body—and when does it fail?',action:'Interrupt reactions',do:'First interrupt the chemistry. Then choose RESTORE, or let the remaining catalysts decay longer. Restoration changes only the reaction coefficient. It never reloads an earlier shape.',why:'Early recovery and late failure separate a working generative rule from the surviving material state it still requires. Try both branches.',quote:'All inferences from experience, therefore, are effects of custom, not of reasoning',author:'David Hume · An Enquiry Concerning Human Understanding, V',url:'https://www.gutenberg.org/files/9662/9662-h/9662-h.htm'},
 {id:'holo',n:'07',title:'Holobiont / dependence',q:'Do the two populations persist together but not separately?',action:'Run the three controls',do:'The large sample retains A+B. In the small controls, one partner is converted to precursor, keeping the same total material. All three then obey the identical reaction law.',why:'This deliberately mutual-catalytic model sustains a shared chemical body. The controls expose that dependence instead of awarding a generic “symbiosis” energy bonus.',quote:'The relation of organism to organism the most important of all relations.',author:'Charles Darwin · On the Origin of Species, contents of Chapter III',url:'https://www.gutenberg.org/files/1228/1228-h/1228-h.htm'}
];
const grid=document.getElementById('grid');
for(const d of defs){
 const holo=d.id==='holo';
 grid.insertAdjacentHTML('beforeend',`<article id="${d.id}" class="experiment ${holo?'wide':''}"><div class="cardhead"><span class="eyebrow">${d.n} / ONE CONTROLLED QUESTION</span><h2>${d.title}</h2><p class="question">${d.q}</p></div><div class="cardbody"><div><div class="viewport"><canvas class="bodycanvas" id="view-${d.id}" aria-label="${d.title}: active and dissolved material"></canvas><span class="stamp">${holo?'A + B / PAIRED':'EXPERIMENT'}</span><span class="time" id="time-${d.id}">READY</span><span class="pointerhint">${d.id==='wound'?'Tap anywhere in the body to puncture it':d.id==='turnover'?'PALE = ORIGINAL  ·  GOLD = NEW':d.id==='memory'?'CORAL = RETAINED CHEMICAL TRACE':'Bright = active body · dim = dissolved precursor'}</span>${holo?'':`<div class="thumbnail"><canvas id="control-${d.id}"></canvas><div>${d.id==='assembly'?'coupling off':d.id==='memory'?'same pulse / no trace':'matched control'}</div></div>`}</div>${holo?`<div class="paircontrols"><figure><canvas id="only-a"></canvas><figcaption>A only <span id="only-a-value">READY</span></figcaption></figure><figure><canvas id="only-b"></canvas><figcaption>B only <span id="only-b-value">READY</span></figcaption></figure></div>`:''}</div><div><div class="stats" id="stats-${d.id}"><div class="stat"><strong>—</strong><span>Growing baseline</span></div></div><div class="actions"><button disabled class="primary" id="go-${d.id}">${d.action}</button><button disabled class="secondary" id="reset-${d.id}">Reset</button>${d.id==='restore'?'<button class="secondary wait hidden" id="late">Let it decay</button>':''}${d.id==='memory'?'<button class="secondary hidden" id="erase">Erase trace</button>':''}</div><p class="status" id="status-${d.id}">Preparing the shared starting condition.</p><div class="plot"><canvas id="plot-${d.id}"></canvas><div class="plotlabel"><span>${d.id==='turnover'?'GOLD original fraction · BLUE body area':'GOLD experiment area · BLUE matched control'}</span><span>model time →</span></div></div><div class="copy"><p><b>Do this.</b> ${d.do}</p><p><b>Why it is beautiful.</b> ${d.why}</p><div class="quote">“${d.quote}”<a href="${d.url}" target="_blank" rel="noopener">${d.author} ↗</a></div></div></div></div></article>`);
}
function clamp(x,a=0,b=1){return Math.min(b,Math.max(a,x));}
function fit(c){const w=c.clientWidth||300,h=c.clientHeight||200,r=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(w*r)||c.height!==Math.round(h*r)){c.width=Math.round(w*r);c.height=Math.round(h*r);}const g=c.getContext('2d');g.setTransform(r,0,0,r,0,0);return{g,w,h};}
class Renderer{
 constructor(c){this.c=c;this.off=document.createElement('canvas');this.off.width=W;this.off.height=W;this.og=this.off.getContext('2d');this.image=this.og.createImageData(W,W);this.u=new Float64Array(S);this.box={x:0,y:0,side:1};}
 draw(model,view='plain',mark){const {g,w,h}=fit(this.c),pix=this.image.data,u=this.u;
  for(let i=0;i<S;i++)u[i]=model.a[i]+model.b[i];
  for(let i=0;i<S;i++){
   const v=u[i],bath=clamp(model.q[i]/2.4),f=clamp(v/2.5),old=model.oa?clamp((model.oa[i]+model.ob[i])/Math.max(v,1e-50)):1;
   let col=view==='a'?[125,213,227]:view==='b'?[239,164,122]:[218,235,222];
   if(model.oa)col=[218*old+241*(1-old),235*old+180*(1-old),222*old+89*(1-old)];
   if(view==='memory'){const m=clamp(model.m[i]*1.25);col=[col[0]*(1-m)+250*m,col[1]*(1-m)+109*m,col[2]*(1-m)+98*m];}
   const j=i*4,x=i%W,y=Math.floor(i/W),gx=x>0&&x<W-1?u[i+1]-u[i-1]:0,gy=y>0&&y<W-1?u[i+W]-u[i-W]:0;
   const shade=clamp(.83-.14*gx-.22*gy,.45,1.13),alpha=Math.pow(f,.77),bg=[8+bath*8,15+bath*19,21+bath*23];
   pix[j]=clamp(bg[0]*(1-alpha)+col[0]*alpha*shade,0,255);pix[j+1]=clamp(bg[1]*(1-alpha)+col[1]*alpha*shade,0,255);pix[j+2]=clamp(bg[2]*(1-alpha)+col[2]*alpha*shade,0,255);pix[j+3]=255;
  }
  this.og.putImageData(this.image,0,0);g.fillStyle='#080f15';g.fillRect(0,0,w,h);
  const side=Math.min(w,h)*(h>150?1.12:.99),ox=(w-side)/2,oy=(h-side)/2;this.box={x:ox,y:oy,side};
  g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(this.off,ox,oy,side,side);
  // This is a measured A+B=1 contour, not a membrane object or a physics constraint.
  g.beginPath();for(let y=0;y<W-1;y++)for(let x=0;x<W-1;x++){
   const i=y*W+x,vs=[u[i],u[i+1],u[i+W+1],u[i+W]],pts=[[x,y],[x+1,y],[x+1,y+1],[x,y+1]],cross=[];
   for(let k=0;k<4;k++){const n=(k+1)%4;if((vs[k]>1)!==(vs[n]>1)){const t=(1-vs[k])/(vs[n]-vs[k]);cross.push([pts[k][0]+t*(pts[n][0]-pts[k][0]),pts[k][1]+t*(pts[n][1]-pts[k][1])]);}}
   for(let k=0;k+1<cross.length;k+=2){g.moveTo(ox+cross[k][0]*side/W,oy+cross[k][1]*side/W);g.lineTo(ox+cross[k+1][0]*side/W,oy+cross[k+1][1]*side/W);}
  }g.strokeStyle=view==='memory'?'#eaa29a':view==='a'?'#98dce7':view==='b'?'#f1b18c':'#c9dccc';g.lineWidth=h>150?1.15:.7;g.globalAlpha=.8;g.stroke();g.globalAlpha=1;
  if(mark){g.beginPath();g.arc(ox+mark.x*side/W,oy+mark.y*side/W,mark.r*side/W,0,Math.PI*2);g.setLineDash([3,4]);g.lineWidth=1;g.strokeStyle='#ed9b8f';g.stroke();g.setLineDash([]);}
 }
 point(clientX,clientY){const r=this.c.getBoundingClientRect();return{x:(clientX-r.left-this.box.x)/this.box.side*W,y:(clientY-r.top-this.box.y)/this.box.side*W};}
}
class Experiment{
 constructor(d){this.d=d;this.id=d.id;this.el=document.getElementById(d.id);this.renderer=new Renderer(document.getElementById('view-'+d.id));this.ctrlRenderer=d.id!=='holo'?new Renderer(document.getElementById('control-'+d.id)):null;if(d.id==='holo'){this.ra=new Renderer(document.getElementById('only-a'));this.rb=new Renderer(document.getElementById('only-b'));}
  this.go=document.getElementById('go-'+d.id);this.stat=document.getElementById('stats-'+d.id);this.status=document.getElementById('status-'+d.id);this.chart=document.getElementById('plot-'+d.id);this.visible=true;this.go.onclick=()=>this.action();document.getElementById('reset-'+d.id).onclick=()=>this.reset();this.go.disabled=false;document.getElementById('reset-'+d.id).disabled=false;
  if(d.id==='wound'){let down;this.renderer.c.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});this.renderer.c.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>10)return;const p=this.renderer.point(e.clientX,e.clientY);if(p.x>=0&&p.x<W&&p.y>=0&&p.y<W)this.injure(p.x,p.y,7);down=null;});}
  if(d.id==='restore')document.getElementById('late').onclick=()=>{this.begin('exhaust',150,30);this.events.push({kind:'prolong-interruption',time:this.model.time});};
  if(d.id==='memory')document.getElementById('erase').onclick=()=>{this.model.m.fill(0);this.model.learn=0;this.begin('erasing',6500,900);this.events.push({kind:'erase-local-trace',time:this.model.time});};
  this.reset();
 }
 reset(){this.model=this.id==='assembly'?new Model(seed):baseline.clone();this.control=this.model.clone();if(this.id==='assembly')this.control.coupling=0;this.reference=baseline.metrics();this.startTime=this.model.time;this.run=false;this.localPause=false;this.phase='ready';this.count=0;this.budget=0;this.history=[];this.events=[];this.mark=null;this.region=[];this.hold=0;this.completeAge=0;this.lethal=false;if(this.id==='holo'){this.onlyA=baseline.clone();this.onlyB=baseline.clone();this.onlyA.isolate('a');this.onlyB.isolate('b');}if(this.id==='restore')document.getElementById('late').classList.add('hidden');if(this.id==='memory')document.getElementById('erase').classList.add('hidden');this.sample();this.render();}
 begin(phase,target,rate){this.phase=phase;this.target=target;this.count=0;this.budget=0;this.rate=rate;this.run=true;this.localPause=false;this.completeAge=0;this.render();}
 action(){if(this.run){this.localPause=!this.localPause;this.render();return;}
  if(this.id==='restore'&&(this.phase==='interrupted'||this.phase==='depleted')){this.model.coupling=1;this.events.push({kind:'restore-coupling',time:this.model.time});document.getElementById('late').classList.add('hidden');this.begin('restoring',5500,900);return;}
  if(this.id==='wound'){this.injure(32,32,8);return;}
  this.reset();this.events.push({kind:'start-'+this.id,time:this.model.time});
  if(this.id==='assembly')this.begin('assembling',20000,1500);
  if(this.id==='turnover'){this.model.label();this.model.wash=.12;this.begin('washing',8500,700);}
  if(this.id==='memory'){this.model.pulse();this.control.pulse();this.model.learn=.2;this.model.stimulus=this.control.stimulus=.5;this.begin('training',700,240);}
  if(this.id==='lost'){this.model.coupling=0;this.begin('losing',100,18);}
  if(this.id==='restore'){this.model.coupling=0;this.begin('interrupting',30,12);}
  if(this.id==='holo'){this.onlyA.isolate('a');this.onlyB.isolate('b');this.begin('comparing',150,22);}
 }
 injure(x,y,r){this.control=this.model.clone();this.reference=this.control.metrics();this.startTime=this.model.time;this.history=[];this.sample();this.region=this.model.puncture(x,y,r).filter(i=>this.control.a[i]+this.control.b[i]>1);this.mark={x,y,r};this.events.push({kind:'puncture',x,y,r,time:this.model.time});this.hold=1.15;this.begin('punctured',6500,850);this.sample();this.render();}
 advance(n){if(!this.run||this.localPause)return;let left=n;
  while(left>0&&this.run){const k=Math.min(left,this.target-this.count);if(k>0){this.model.step(k);this.control.step(k);if(this.id==='holo'){this.onlyA.step(k);this.onlyB.step(k);}this.count+=k;left-=k;}if(this.count>=this.target)this.finishStage();if(k===0)break;}
  this.sample();
 }
 finishStage(){if(this.phase==='training'){this.model.stimulus=this.control.stimulus=0;this.events.push({kind:'pulse-ended',time:this.model.time});this.begin('relaxing',4500,950);return;}
  if(this.phase==='interrupting'){this.run=false;this.phase='interrupted';document.getElementById('late').classList.remove('hidden');return;}
  if(this.phase==='exhaust'){this.run=false;this.phase='depleted';this.lethal=true;document.getElementById('late').classList.add('hidden');return;}
  this.run=false;this.phase='complete';this.completeAge=0;this.mark=null;if(this.id==='memory')document.getElementById('erase').classList.remove('hidden');
 }
 tick(dt){if(paused||!this.visible||this.localPause)return;if(this.run){if(this.hold>0){this.hold-=dt;if(this.hold<=0)this.phase='repairing';return;}this.budget+=dt*this.rate;const n=Math.min(100,Math.floor(this.budget));if(n){this.budget-=n;this.advance(n);}}else if(this.id==='restore'&&this.phase==='interrupted'&&document.getElementById('loop').checked){this.completeAge+=dt;if(this.completeAge>2)this.action();}else if(this.phase==='complete'&&document.getElementById('loop').checked){this.completeAge+=dt;if(this.completeAge>4){this.reset();this.action();}}}
 sample(){const m=this.model.metrics(),c=this.control.metrics();if(m.min< -1e-9||!Number.isFinite(m.total)||Math.abs(m.total-this.reference.total)>1e-4){this.run=false;this.phase='error';}const p={time:this.model.time-this.startTime,area:m.area/Math.max(1,this.reference.area),control:c.area/Math.max(1,this.reference.area),original:m.original,trace:m.trace,material:m.total/this.reference.total};if(this.history.length<1500)this.history.push(p);else this.history=this.history.filter((_,i)=>i%2===0);this.metrics=m;this.cm=c;}
 measures(){const m=this.metrics;let items=[[(m.area/this.reference.area*100).toFixed(0)+'%','body area / before'],[(m.total/this.reference.total*100).toFixed(1)+'%','total material'],[this.phase==='ready'?'READY':this.run?'RUNNING':'HELD','observation']];
  if(this.id==='assembly')items=[[m.area.toFixed(0),'active grid sites'],[String(this.model.components().length),'connected regions'],[(this.cm.area).toFixed(0),'control active sites']];
  if(this.id==='turnover')items=[[m.original<.001?'<0.1%':(m.original*100).toFixed(1)+'%','original material'],[m.original<.001?'>99.9%':((1-m.original)*100).toFixed(1)+'%','new material'],[(m.area/Math.max(1,this.cm.area)*100).toFixed(1)+'%','area / matched control']];
  if(this.id==='wound'){const filled=this.region.length?this.region.filter(i=>this.model.a[i]+this.model.b[i]>1).length/this.region.length:1;items=[[this.region.length?(100*filled).toFixed(0)+'%':'—','hole sites restored'],[(m.area/this.reference.area*100).toFixed(0)+'%','body area / before'],[(m.total/this.reference.total*100).toFixed(1)+'%','total material']];}
  if(this.id==='memory'){let dif=0;for(let i=0;i<S;i++)dif+=Math.abs(this.model.a[i]+this.model.b[i]-this.control.a[i]-this.control.b[i]);this.divergence=dif/Math.max(1e-20,this.cm.active);items=[[this.model.stimulus?'ON':'OFF','external pulse'],[m.trace.toFixed(1),'retained trace / units'],[(this.divergence*100).toFixed(1)+'%','difference from control']];}
  if(this.id==='lost'||this.id==='restore')items=[[(m.area/this.reference.area*100).toFixed(0)+'%','body area / before'],[(m.total/this.reference.total*100).toFixed(1)+'%','material still here'],[this.model.coupling?'ON':'OFF','catalytic coupling']];
  if(this.id==='holo'){const a=this.onlyA.metrics(),b=this.onlyB.metrics();items=[[(a.area/this.reference.area*100).toFixed(0)+'%','A-only body area'],[(b.area/this.reference.area*100).toFixed(0)+'%','B-only body area'],[(m.area/this.reference.area*100).toFixed(0)+'%','paired body area']];document.getElementById('only-a-value').textContent=a.area?'ACTIVE':'DISSOLVED';document.getElementById('only-b-value').textContent=b.area?'ACTIVE':'DISSOLVED';}
  this.stat.innerHTML=items.map(([v,k])=>`<div class="stat"><strong>${v}</strong><span>${k}</span></div>`).join('');
 }
 message(){if(this.phase==='error')return '<b>Numerical check failed.</b> This run has stopped rather than displaying an invalid result.';if(this.localPause)return '<b>Paused.</b> The material state and model time are held.';if(this.phase==='ready')return '<b>Ready.</b> Start the intervention when you are watching. Results will stay on screen.';
  const messages={assembling:'<b>Assembling.</b> Local synthesis and diffusion are making the boundary. The control has no coupling.',washing:'<b>Material exchange is running.</b> Gold tracks incoming material—not a timed colour effect.',punctured:'<b>Hole applied.</b> Briefly held so you can inspect what was removed from the active body.',repairing:'<b>No repair command.</b> Only the same reactions and diffusion are running.',training:'<b>Identical pulse in both samples.</b> Only the main sample can form a chemical trace.',relaxing:'<b>Pulse OFF.</b> Coral shows the material trace that remains after the stimulus.',erasing:'<b>Trace erased.</b> The current body was kept; only the stored catalyst modification was removed.',losing:'<b>Coupling OFF.</b> Active material is becoming dissolved precursor, not leaving the universe.',interrupting:'<b>Interrupting.</b> The boundary is fading while residual catalysts remain.',interrupted:'<b>Your choice.</b> Restore now—or let the remaining catalysts decay further before trying.',exhaust:'<b>Waiting longer with reactions OFF.</b> No new damage or material deletion is applied.',depleted:'<b>Longer interruption complete.</b> Try restoring the rule. Recovery is not guaranteed.',restoring:'<b>Coupling restored.</b> No previous concentrations or coordinates were reloaded.',comparing:'<b>Three controlled samples.</b> Same material total and local law; different availability of the partner.'};
  if(this.phase!=='complete')return messages[this.phase]||'';
  if(this.id==='assembly')return this.model.components().length===1?'<b>One connected chemical body formed.</b> Compare the same seed with coupling disabled.':'<b>Assembly result held.</b> This seed did not form one connected body.';
  if(this.id==='turnover')return '<b>Exchange result held.</b> '+(this.metrics.original<.001?'More than 99.9% of active material is new.':'Some original material remains.')+' Compare the body with the matched control.';
  if(this.id==='wound'){const closure=this.region.length?this.region.filter(i=>this.model.a[i]+this.model.b[i]>1).length/this.region.length:0;return closure>.95?'<b>The puncture closed under local chemistry.</b> This measures closure, not an exact restoration of every concentration.':'<b>Recovery was incomplete.</b> The remaining gap is part of the result—not hidden by a reset.';}
  if(this.id==='memory')return '<b>Stimulus absent; response differs.</b> The trace and matched-control difference are measured above. Erase the trace to test its role.';
  if(this.id==='lost')return this.metrics.area===0?'<b>Material remains; the high-density body is gone.</b> The control kept its coupling.':'<b>Interruption result held.</b> Some high-density body remains under these conditions.';
  if(this.id==='restore')return this.metrics.area>.8*this.reference.area?'<b>Body recovered from surviving chemistry.</b> Reset and try the longer interruption to test the limit.':'<b>No body recovered.</b> Restoring the rule was not enough after the longer interruption.';
  if(this.id==='holo')return '<b>Compare together against separately.</b> This tests the designed chemical dependence—not a claim that every microbiome behaves this way.';return '';
 }
 plot(){const{g,w,h}=fit(this.chart);g.clearRect(0,0,w,h);g.strokeStyle='#26343e';g.lineWidth=1;g.beginPath();g.moveTo(0,h-9);g.lineTo(w,h-9);g.moveTo(0,12);g.lineTo(w,12);g.stroke();if(this.history.length<2)return;const maxT=Math.max(.01,this.history[this.history.length-1].time),ys=1.4;
  const line=(key,col,dash=[])=>{g.strokeStyle=col;g.setLineDash(dash);g.lineWidth=1.5;g.beginPath();this.history.forEach((p,i)=>{const x=p.time/maxT*(w-2),y=h-9-clamp(p[key],0,ys)/ys*(h-14);if(i)g.lineTo(x,y);else g.moveTo(x,y);});g.stroke();g.setLineDash([]);};
  if(this.id==='turnover'){line('original','#e6b76f');line('area','#83c4d0',[3,3]);}else{line('control','#83c4d0',[3,3]);line('area','#e6b76f');}
 }
 render(){this.measures();this.renderer.draw(this.model,this.id==='memory'?'memory':'plain',this.hold>0?this.mark:null);if(this.ctrlRenderer)this.ctrlRenderer.draw(this.control);if(this.ra){this.ra.draw(this.onlyA,'a');this.rb.draw(this.onlyB,'b');}this.plot();this.status.innerHTML=this.message();document.getElementById('time-'+this.id).textContent='t +'+(this.model.time-this.startTime).toFixed(1)+' MODEL UNITS';this.go.textContent=this.run?(this.localPause?'Resume':'Pause'):this.id==='restore'&&(this.phase==='interrupted'||this.phase==='depleted')?'Restore only the rule':this.phase==='complete'?(this.id==='wound'?'Puncture again':'Replay experiment'):this.d.action;}
 export(){return{id:this.id,phase:this.phase,seed,events:this.events,metrics:this.model.metrics(),history:this.history,control:this.control.metrics()};}
}
function fail(e){const node=document.getElementById('loading');node.className='error';node.textContent='Simulation could not start: '+(e.message||e)+'. The error is shown instead of a blank canvas.';console.error(e);}
async function init(){
 document.getElementById('seedlabel').textContent='SEED '+seed+' · 64×64 · FIXED Δt 0.04';
 baseline=new Model(seed);for(let i=0;i<20000;i+=250){baseline.step(250);document.getElementById('progress').value=i+250;await new Promise(requestAnimationFrame);}
 experiments=defs.map(d=>new Experiment(d));
 const obs=new IntersectionObserver(entries=>{for(const en of entries){const ex=experiments.find(x=>x.el===en.target);if(ex)ex.visible=en.isIntersecting;}},{rootMargin:'150px'});experiments.forEach(e=>obs.observe(e.el));
 const load=document.getElementById('loading');load.innerHTML='BASELINE GROWN · '+baseline.components().length+' connected region(s) · same seed in every test. Runs pause off-screen.';ready=true;
 window.continuityLab={experiments,baseline,seed,Model,export:()=>experiments.map(e=>e.export())};requestAnimationFrame(frame);
}
let drawClock=0;
function frame(now){const dt=last?Math.min((now-last)/1000,.08):0;last=now;drawClock+=dt;try{for(const e of experiments)e.tick(dt);if(drawClock>.066){drawClock=0;for(const e of experiments)if(e.visible)e.render();}}catch(err){fail(err);paused=true;}requestAnimationFrame(frame);}
document.getElementById('pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume all':'Pause all';};
document.getElementById('newseed').onclick=()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);const u=new URL(location.href);u.searchParams.set('seed',String(a[0]||1));u.searchParams.set('v','10');location.href=u.href;};
document.getElementById('export').onclick=()=>{if(!ready)return;const data={build:10,model:'two-catalyst reaction-diffusion',seed,dt:.04,grid:64,experiments:experiments.map(e=>e.export())};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='continuity-observations-'+seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
init().catch(fail);
})();
